# This is a basic workflow to help you get started with Actions

name: ReadtheDocs

# Controls when the action will run. Triggers the workflow on push events
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job builds the docs.
  build_docs_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my documentation
      uses: actions/checkout@v1
    - name: Build Docs
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs"
        pre-build-command: "pip install sphinx_rtd_theme"
    - name: Commit documentation changes
      run: |
        git clone https://github.com/DivSeek-Canada/divseek-canada-docs.git --branch master --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: master
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
